blog/urls.py
# blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('blog/', views.BlogListView.as_view(), name='blog-list'),
    path('post/<slug:slug>/', views.BlogDetailView.as_view(), name='blog-detail'),
    path('blog/category/<slug:slug>/', views.CategoryPostListView.as_view(), name='category-posts'),
    path('tag/<slug:slug>/', views.TagPostListView.as_view(), name='tag-posts'),
    path('admin/posts/all', views.BlogPostListAdminView.as_view(), name='blog-list-admin'),
    path('admin/post/create/', views.BlogPostCreateView.as_view(), name='blog-create'),
    path('admin/post/<int:pk>/update/', views.BlogPostUpdateView.as_view(), name='blog-update'),
    path('admin/post/<int:pk>/delete/', views.BlogPostDeleteView.as_view(), name='blog-delete'),
   
]

courses/urls.py
from django.urls import path

from . import views
from .views import CourseAutocomplete,InstructorAutocomplete,PartnerAutocomplete
app_name = 'courses'

urlpatterns = [
    path('courses/', views.courseView, name='course_view'),
    path('course/<int:course_id>/enroll/', views.enroll_course, name='enroll_course'),
    path('instructor-add/', views.become_instructor, name='instructor_add'),
    path('partner-autocomplete/', PartnerAutocomplete.as_view(), name='partner-autocomplete'),
    path('partner-autocomplete/', views.partner_autocomplete, name='partner_autocomplete'),
    path('instructor/', views.instructor_view, name='instructor_view'),
    path('instructor/<int:instructor_id>/check/', views.instructor_check, name='instructor_check'),
    path('instructor/<int:instructor_id>/delete/', views.delete_instructor, name='delete_instructor'),
    path('instructor/<int:id>/', views.instructor_detail, name='instructor_detail'),
    path('instructor-profile/<slug:username>/', views.instructor_profile, name='instructor_profile'),
    path("studio/<str:id>", views.studio, name= "studio"),
    path('reorder-section/', views.reorder_section, name='reorder_section'),
    path("partner/", views.partnerView, name= "partner_view"),
    path('partner/<int:partner_id>/', views.partner_detail, name='partner_detail'),
    path('partner/<int:partner_id>/update/', views.update_partner, name='update_partner'),
    path('org-partner/<slug:slug>/',views.org_partner, name='org_partner'),
   
    path("course-add/", views.course_create_view, name= "course_create_view"),
    path("category/add/", views.category_create_view, name= "category_create_view"),
    path("partner-add/", views.partner_create_view, name= "partner_create_view"),
    path('user-autocomplete/', views.UserAutocomplete.as_view(), name='user-autocomplete'),
    path('universiti-autocomplete/', views.UniversitiAutocomplete.as_view(), name='universiti-autocomplete'),
    path('create-section/<int:idcourse>/', views.create_section, name='create_section'),
    path('add-matrial/<int:idcourse>/<int:idsection>/',views.add_matrial,name="add-matrial"),
    path('create-assessment/<int:idcourse>/<int:idsection>/', views.create_assessment, name='create-assessment'),
    path('edit-assessment/<int:idcourse>/<int:idsection>/<int:idassessment>/', views.edit_assessment, name='edit_assessment'),
    path('delete-assessment/<int:idcourse>/<int:idsection>/<int:idassessment>/', views.delete_assessment, name='delete_assessment'),
    path('course-list-enroll/<int:id>/', views.course_list_enroll, name='course_list_enroll'),



    
    
    path('questions/create/<int:idcourse>/<int:idsection>/<int:idassessment>/', views.create_question_view, name='create_question'),
    path('edit-matrial/<int:idcourse>/<int:idmaterial>', views.edit_matrial, name='edit_matrial'),
    path('questions/edit/<int:idcourse>/<int:idquestion>/<int:idsection>/<int:idassessment>', views.edit_question, name='edit_question'),
    path('questions/delete/<int:idcourse>/<int:idquestion>/<int:idsection>/<int:idassessment>', views.delete_question, name='delete_question'),
    path(
        'questions/view/<int:idcourse>/<int:idsection>/<int:idassessment>/',
        views.question_view,
        name='view-question',
    ),
    path('delete-matrial/<int:pk>', views.delete_matrial, name='delete_matrial'),
    path('delete-section/<int:pk>/', views.delete_section, name='delete_section'),
    path('update-section/<int:pk>/', views.update_section, name='update_section'),
    path('course-profile/<int:id>/', views.course_profile, name='course_profile'),
    path('course-grade/<int:id>/', views.course_grade, name='course_grade'),
    path("update-grade-range/<int:id>/", views.update_grade_range, name="update_grade_range"),
    path('course-team/<int:id>/', views.course_team, name='course_team'),
    path('course-instructor/<int:id>/', views.course_instructor, name='course_instructor'),
    path('instructor-autocomplete/', InstructorAutocomplete.as_view(), name='instructor-autocomplete'),
    
    path('team-member/remove/<int:member_id>/', views.remove_team_member, name='remove_team_member'),
    path('draft-lms/<int:id>/', views.draft_lms, name='draft-lms'),
    path('course-detail/<int:id>/<slug:slug>/', views.course_lms_detail, name='course_lms_detail'),

    path('add-price/<int:id>/', views.add_course_price, name='add_course_price'),
    path('course/<int:id>/<slug:slug>/rating/', views.submit_rating, name='submit_rating'),
    path('courses/re-runs/<int:id>/', views.course_reruns, name='course_reruns'),
    path('course-learn/<str:username>/<slug:slug>/', views.course_learn, name='course_learn'),
    path('self_course/<str:username>/<int:id>/<slug:slug>/', views.self_course, name='self_course'),
    path('submit_assessment/<int:assessment_id>/', views.submit_assessment, name='submit_assessment'),
    path('start-assessment/<int:assessment_id>/', views.start_assessment, name='start_assessment'),
    path('enroll/<int:course_id>/', views.enroll_course, name='enroll'),  # Define 'enroll' URL pattern
    path('add-comment/<int:material_id>/', views.add_comment, name='add_comment'),
    path('add-comment-course/<int:course_id>/', views.add_comment_course, name='add_comment_course'),  # Add this line
    path('course/<int:idcourse>/section/<int:idsection>/assessment/<int:idassessment>/create/', views.create_askora, name='create_askora'),
    #add lti 1.1
    path('course/<int:idcourse>/section/<int:idsection>/lti/<int:idlti>/create/', views.create_lti, name='create_lti'),
    path('course/<int:idcourse>/section/<int:idsection>/lti/<int:idlti>/edit/<int:id_lti_tool>/', views.edit_lti, name='edit_lti'),
    path('course/<int:idcourse>/section/<int:idsection>/lti/<int:idlti>/delete/<int:id_lti_tool>/', views.delete_lti, name='delete_lti'),
    path('course/<int:idcourse>/section/<int:idsection>/lti/<int:idlti>/launch/<int:id_lti_tool>/', views.launch_lti, name='launch_lti'),
    
    path('edit-askora/<int:idcourse>/<int:idaskora>/<int:idsection>/<int:idassessment>/', views.edit_askora, name='edit_askora'),
    path('delete-askora/<int:idcourse>/<int:idaskora>/<int:idsection>/<int:idassessment>/', views.delete_askora, name='delete_askora'),
    #sertifikat
    path('certificate/<int:course_id>/', views.generate_certificate, name='generate_certificate'),
    path('verify/<uuid:certificate_id>/', views.verify_certificate, name='verify_certificate'),
    path('verify-micro/<uuid:certificate_id>/', views.verify_certificate_micro, name='verify_certificate_micro'),
    path('submit-answer/<int:askora_id>/', views.submit_answer, name='submit_answer'),
    path('submit-peer-review/<int:submission_id>/', views.submit_peer_review, name='submit_peer_review'),

    path('microcredentials/', views.listmic, name='microcredential-list'),
    path('microcredentials/create/', views.addmic, name='microcredential-create'),
    path('course-autocomplete/', CourseAutocomplete.as_view(), name='course-autocomplete'),

    path('microcredentials/<int:pk>/edit/', views.editmic, name='microcredential-update'),
    path('microcredentials/<int:pk>/delete/', views.deletemic, name='microcredential-delete'),
    path('microcredentials/<int:pk>/', views.detailmic, name='microcredential-detail'),  # Detail view
    path('microcredential/<slug:slug>/', views.microcredential_detail, name='microcredential_detail'),
    path('microcredential/<int:id>/certificate/', views.generate_microcredential_certificate, name='generate_microcredential_certificate'),
    path('microcredential/<slug:slug>/enroll/', views.enroll_microcredential, name='enroll_microcredential'),
    #detail micro lms
    path('microcredential/<int:id>/<slug:slug>/detail/', views.micro_detail, name='micro_detail'),
    path('microcredential/<int:microcredential_id>/add-review/', views.add_microcredential_review, name='add_microcredential_review'),
    path('microcredential/<int:microcredential_id>/<slug:slug>/add_comment/', views.add_comment_microcredential, name='add_comment_microcredential'),
    path('microcredential/<int:microcredential_id>/report/', views.microcredential_report_view, name='microcredential_report'),
    path('microcredential/report/pdf/<int:microcredential_id>/', views.microcredential_report_pdf_view, name='microcredential_report_pdf'),

    path('comment/<int:comment_id>/reply/', views.reply_comment, name='reply_comment'),
    path('sosial/', views.create_and_list_sos_posts, name='create_and_list_sos_posts'),
    path('sosial/create/', views.create_post, name='create_post'),
    path('sosial/like/<int:post_id>/', views.like_post, name='like_post'),
   
    path('sosial/reply/<int:post_id>/', views.reply_post, name='reply_post'),
    path('sosial/reply-form/<int:post_id>/', views.reply_form, name='reply_form'),  # Ditambahkan
    path('sosial/hashtag/<str:hashtag>/', views.posts_by_hashtag, name='posts_by_hashtag'),  # Rute baru
    path('sosial/load-more/', views.load_more_posts, name='load_more_posts'),
    path('sosial/search/', views.search_posts, name='search_posts'),  # Rute baru
   #menuju home category
    path('category/<slug:slug>/', views.category_course_list, name='category_list'),

 
    
]

licensing/urls.py
from django.urls import path
from . import views

app_name = 'licensing'

urlpatterns = [
    path('dashboard/', views.licens_dashboard, name='licens_dashboard'),
    path('learners/', views.licens_learners, name='licens_learners'),
    path('license/analytics/', views.licens_analytics, name='licens_analytics'),
    path('participant/dashboard/', views.participant_dashboard, name='participant_dashboard'),
    path('invitation/send/', views.send_invitation, name='send_invitation'),
    path('invitation/cancel/<int:invitation_id>/', views.cancel_invitation, name='cancel_invitation'),
    path('invitation/resend/<int:invitation_id>/', views.resend_invitation, name='resend_invitation'),
    path('invitation/accept/<str:uidb64>/<str:token>/', views.accept_invitation, name='accept_invitation'),
    path('invitation/delete/<int:invitation_id>/', views.delete_invitation, name='delete_invitation'),  # Baru
    path('course-participants-dashboard/', views.course_participants_dashboard, name='course_participants_dashboard'),
    path('course-detail/<int:course_id>/', views.course_detail, name='course_detail'),
    path('create/', views.license_create, name='license_create'),
    path('update/<int:pk>/', views.license_update, name='license_update'),
    path('manage/', views.subscription_management, name='subscription_management'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('authentication.urls')),
    path('', include('courses.urls', namespace='courses')),
    path('', include('partner.urls', namespace='partner')),
    path('', include('instructor.urls', namespace='instructor')),
    path('', include('learner.urls', namespace='learner')),
    path('', include('blog.urls', namespace='blog')),
    path('', include('licensing.urls', namespace='licensing')),
    path('', include('payments.urls', namespace='payments')),
    path('', include("lti_consumer.urls", namespace="lti_consumer")),
    path('kuruk/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('accounts/',include("allauth.urls")),
    path('select2/', include('django_select2.urls')),  # <- tambahkan ini
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    path("ckeditor5/", include('django_ckeditor_5.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

licensing/models.py
from django.db import models
import uuid
from django.contrib.auth import get_user_model
from django.utils import timezone
from authentication.models import Universiti
from django.conf import settings

User = get_user_model()

class License(models.Model):
    LICENSE_TYPE_CHOICES = [
        ('free', 'Gratis'),
        ('paid', 'Berbayar'),
        ('trial', 'Uji Coba'),
    ]
    SUBSCRIPTION_FREQUENCY_CHOICES = [
        ('monthly', 'Bulanan'),
        ('yearly', 'Tahunan'),
        ('once', 'Sekali'),
    ]
    
    users = models.ManyToManyField(User, related_name='licenses', verbose_name='Pengguna')
    name = models.CharField(max_length=255, verbose_name='Nama Lisensi')
    license_type = models.CharField(max_length=10, choices=LICENSE_TYPE_CHOICES, default='trial', verbose_name='Tipe Lisensi')
    start_date = models.DateField(default=timezone.now, verbose_name='Tanggal Mulai')
    expiry_date = models.DateField(verbose_name='Tanggal Berakhir')
    status = models.BooleanField(default=True, verbose_name='Status')
    description = models.TextField(blank=True, null=True, verbose_name='Deskripsi')
    university = models.ForeignKey(Universiti, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Universitas')
    max_users = models.PositiveIntegerField(default=20, verbose_name='Maksimum Pengguna')
    
    subscription_type = models.CharField(max_length=20, choices=LICENSE_TYPE_CHOICES, default='paid', verbose_name='Tipe Langganan')
    subscription_frequency = models.CharField(max_length=20, choices=SUBSCRIPTION_FREQUENCY_CHOICES, default='yearly', verbose_name='Frekuensi Langganan')
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='owned_licenses',
        verbose_name='Pemilik Lisensi'
    )
    def __str__(self):
        return f"{self.name}"
    
    class Meta:
        verbose_name = 'Lisensi'
        verbose_name_plural = 'Lisensi'
    
    def is_expired(self):
        return timezone.now().date() > self.expiry_date
    
    def is_approaching_expiry(self, days=7):
        return self.expiry_date <= timezone.now().date() + timezone.timedelta(days=days)
    
    def save(self, *args, **kwargs):
        if self.is_expired():
            self.status = False
        super().save(*args, **kwargs)
    
    def extend_license(self):
        if self.subscription_frequency == 'monthly':
            self.expiry_date += timezone.timedelta(days=30)
        elif self.subscription_frequency == 'yearly':
            self.expiry_date += timezone.timedelta(days=365)
        self.save()
    
    def can_add_user(self):
        return self.users.count() < self.max_users

    @property
    def remaining_slots(self):
        return self.max_users - self.users.count()

class Invitation(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Menunggu'),
        ('accepted', 'Diterima'),
        ('expired', 'Kadaluarsa'),
    ]

    inviter = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_invitations', verbose_name='Pengundang')
    invitee_email = models.EmailField(verbose_name='Email Penerima')
    license = models.ForeignKey(License, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Lisensi Terkait')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending', verbose_name='Status')
    invitation_date = models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Undangan')
    expiry_date = models.DateTimeField(default=timezone.now() + timezone.timedelta(days=7), verbose_name='Tanggal Kadaluarsa')
    token = models.CharField(max_length=255, blank=True, null=True, unique=True, verbose_name='Token')

    def save(self, *args, **kwargs):
        if not self.token:
            self.token = str(uuid.uuid4())
        super().save(*args, **kwargs)
    
    def __str__(self):
        return f"Undangan dari {self.inviter.username} ke {self.invitee_email}"
    
    def is_expired(self):
        return timezone.now() > self.expiry_date

templates/licensing/licens_analytics.html
{% extends 'home/tes.html' %}

{% block content %}

<div class="d-flex justify-content-between align-items-center mb-3">
    <div>
        <h2 class="mb-0">Invitation Analytics</h2>
        <p class="text-muted mb-0">Statistics and list of invitations that have been sent.</p>
    </div>
    <a href="{% url 'licensing:send_invitation' %}" class="btn btn-success">Invite Learners
    <i class="bi bi-person-plus me-2" aria-hidden="true"></i></a>
</div>

<!-- Invitation Statistics -->
<div class="row mb-4">
    <div class="col-md-4">
        <div class="card text-center">
            <div class="card-body">
                <h5 class="card-title">Pending</h5>
                <p class="card-text">{{ invitation_stats.pending }}</p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card text-center">
            <div class="card-body">
                <h5 class="card-title">Accepted</h5>
                <p class="card-text">{{ invitation_stats.accepted }}</p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card text-center">
            <div class="card-body">
                <h5 class="card-title">Expired</h5>
                <p class="card-text">{{ invitation_stats.expired }}</p>
            </div>
        </div>
    </div>
</div>

<!-- Search and Filter Form -->
<form method="GET" class="mb-4">
    <div class="row">
        <div class="col-md-4">
            <input type="text" name="search_query" class="form-control" placeholder="Search by email" value="{{ search_query }}">
        </div>
        <div class="col-md-4">
            <select name="status" class="form-control">
                <option value="">All Statuses</option>
                <option value="pending" {% if status == 'pending' %}selected{% endif %}>Pending</option>
                <option value="accepted" {% if status == 'accepted' %}selected{% endif %}>Accepted</option>
                <option value="expired" {% if status == 'expired' %}selected{% endif %}>Expired</option>
            </select>
        </div>
        <div class="col-md-4">
            <button type="submit" class="btn btn-primary">Search</button>
        </div>
    </div>
</form>

<!-- Invitation List -->
<div class="table-responsive">
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Invitee Email</th>
            <th>Status</th>
            <th>Sent Date</th>
            <th>Expiry Date</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for invitation in invitations %}
        <tr>
            <td>{{ invitation.invitee_email }}</td>
            <td>{{ invitation.status|title }}</td>
            <td>{{ invitation.invitation_date|date:"d M Y" }}</td>
            <td>{{ invitation.expiry_date|date:"d M Y" }}</td>
            <td>
                {% if invitation.status == 'pending' %}
                    <a href="{% url 'licensing:cancel_invitation' invitation.id %}" class="btn btn-sm btn-danger">Cancel</a>
                {% elif invitation.status == 'accepted' %}
                    <a href="{% url 'licensing:delete_invitation' invitation.id %}" class="btn btn-sm btn-warning">Delete</a>
                {% elif invitation.status == 'expired' %}
                    <a href="{% url 'licensing:resend_invitation' invitation.id %}" class="btn btn-sm btn-primary">Resend</a>
                {% endif %}
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="5">No invitations found.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>

<!-- Pagination -->
{% if invitations.has_other_pages %}
<nav aria-label="Page navigation">
    <ul class="pagination">
        {% if invitations.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ invitations.previous_page_number }}{% if status %}&status={{ status }}{% endif %}{% if search_query %}&search_query={{ search_query }}{% endif %}">&laquo; Previous</a>
        </li>
        {% endif %}
        {% for num in invitations.paginator.page_range %}
        <li class="page-item {% if invitations.number == num %}active{% endif %}">
            <a class="page-link" href="?page={{ num }}{% if status %}&status={{ status }}{% endif %}{% if search_query %}&search_query={{ search_query }}{% endif %}">{{ num }}</a>
        </li>
        {% endfor %}
        {% if invitations.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ invitations.next_page_number }}{% if status %}&status={{ status }}{% endif %}{% if search_query %}&search_query={{ search_query }}{% endif %}">Next &raquo;</a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}

{% endblock %}

templates/licensing/licens_dashboard.html
{% extends 'home/tes.html' %}

{% block content %}


   

    <h2>License Dashboard</h2>
    <p>Overview of your licenses, enrollments, and performance metrics.</p>

   
    <!-- Statistik Utama -->
    <div class="row mb-4">
        <div class="col-md-3">
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">Total Enrollments</h5>
                    <p class="card-text">{{ total_enrollments }}</p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">Total Passed</h5>
                    <p class="card-text">{{ total_passed }}</p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">Pass Rate</h5>
                    <p class="card-text">{{ pass_rate }}%</p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">Total Participants</h5>
                    <p class="card-text">{{ total_participants }}</p>
                </div>
            </div>
        </div>
    </div>

    <!-- Statistik Tambahan -->
    <div class="row mb-4">
        <div class="col-md-6">
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">Expiring Licenses (7 Days)</h5>
                    <p class="card-text">{{ expiring_licenses }}</p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">Top Course</h5>
                    <p class="card-text">
                        {% if top_course %}
                        <a href="{% url 'courses:course_lms_detail' id=top_course.course.id slug=top_course.course.slug %}">
                            {{ top_course.course.course_name }}
                            {% if top_course.course.org_partner %}
                                | {{ top_course.course.org_partner.kode|default:top_course.course.org_partner.name|default:"Unknown" }}
                            {% else %}
                                | Unknown
                            {% endif %}
                        </a>
                        ({{ top_course.enrollment_count }} enrollments)
                        {% else %}
                        No courses available
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>
    </div>

    <!-- Aktivitas Terbaru -->
    <div class="card mb-4">
        <div class="card-header">
            <h5>Recent Enrollments</h5>
        </div>
        <div class="card-body">
            <ul class="list-group">
                {% for enrollment in recent_enrollments %}
                <li class="list-group-item">
                    <a href="{% url 'learner:learner_detail' username=enrollment.user.username %}">
                        {{ enrollment.user.get_full_name }}
                    </a>
                    enrolled in
                    <a href="{% url 'courses:course_lms_detail' id=enrollment.course.id slug=enrollment.course.slug %}">
                        {{ enrollment.course.course_name }}
                    </a>
                    on {{ enrollment.enrolled_at|date:"d M Y" }}
                </li>
                {% empty %}
                <li class="list-group-item">No recent enrollments.</li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <!-- Daftar Lisensi dan Kursus -->
    {% if licenses %}
    <div class="row">
        {% for data in license_course_data %}
        <div class="col-md-6 mb-4">
            <div class="card">
                <div class="card-header">
                    <h5>
                        License: {{ data.license.name }}
                        {% if data.days_remaining <= 7 %}
                        <span class="badge bg-danger ms-2">Expiring Soon</span>
                        {% endif %}
                    </h5>
                    <p>
                        ID: {{ data.license.id }} | 
                        Type: {{ data.license.get_license_type_display }}<br>
                        Active: {{ data.license.start_date|date:"d M Y" }} – {{ data.license.expiry_date|date:"d M Y" }} 
                        ({{ data.days_remaining }} days remaining)<br>
                        Users: {{ data.user_count }}/{{ data.license.max_users }} 
                        (Non-admin: {{ data.non_admin_count }})
                    </p>
                </div>
                <div class="card-body">
                    {% if data.non_admin_count == 0 %}
                    <p class="text-warning">No participants added yet.</p>
                    {% endif %}

                    <p><strong>Total Enrollments:</strong> {{ data.enrollment_count }}</p>
                    <p><strong>Total Passed:</strong> {{ data.passed_count }}</p>
                    <h6>Related Courses:</h6>
                    {% if data.courses %}
                    <ul class="list-group">
                        {% for course_data in data.courses %}
                        <li class="list-group-item">
                            <a href="{% url 'courses:course_lms_detail' id=course_data.course.id slug=course_data.course.slug %}">
                                {{ course_data.course.course_name }}
                                {% if course_data.course.org_partner %}
                                    | {{ course_data.course.org_partner.kode|default:course_data.course.org_partner.name|default:"Unknown" }}
                                {% else %}
                                    | Unknown
                                {% endif %}
                            </a>
                            ({{ course_data.enrollment_count }} enrollments)
                        </li>
                        {% empty %}
                        <li class="list-group-item">No related courses.</li>
                        {% endfor %}
                    </ul>
                    {% else %}
                    <p>No related courses for this license.</p>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <div class="alert alert-info">
        You currently have no active licenses.
    </div>
    {% endif %}

{% endblock %}

templates/licensing/participant_dashboard.html
{% extends 'home/base.html' %}
{% block content %}
<div class="container mt-5">
    <h2 class="mb-4">Dashboard Peserta</h2>

    <!-- Menampilkan pesan -->
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}

    <!-- Bagian untuk menampilkan lisensi -->
    <h3 class="mb-3">Lisensi Anda</h3>
    {% if licenses %}
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead class="table-dark">
                    <tr>
                        <th scope="col">Nama Lisensi</th>
                        <th scope="col">Tipe</th>
                        <th scope="col">Tanggal Mulai</th>
                        <th scope="col">Tanggal Berakhir</th>
                        <th scope="col">Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for license in licenses %}
                        <tr>
                            <td>{{ license.name }}</td>
                            <td>{{ license.get_license_type_display }}</td>
                            <td>{{ license.start_date }}</td>
                            <td>{{ license.expiry_date }}</td>
                            <td>
                                {% if license.status %}
                                    <span class="badge bg-success">Aktif</span>
                                {% else %}
                                    <span class="badge bg-danger">Tidak Aktif</span>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <div class="alert alert-info" role="alert">
            Anda belum memiliki lisensi aktif.
        </div>
    {% endif %}
</div>
{% endblock %}